force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApartmentRoom__c/ApartmentRoom__c.object-meta.xml
<CustomObject>
    <label>Apartment Room</label>
    <nameField>
        <label>Apartment Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartment Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApartmentRoom__c/fields/Apartment__c.field-meta.xml
<CustomField>
    <fullName>Apartment__c</fullName>
    <label>Apartment</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipLabel>Apartment Rooms</relationshipLabel>
    <relationshipName>Apartment_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApartmentRoom__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApartmentRoom__c/fields/Price_Per_Night__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Night__c</fullName>
    <label>Price Per Night</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/controllers/ApartmentRoomsControllerTest.cls
@isTest
public with sharing class ApartmentRoomsControllerTest {
    @TestSetup
    static void setup(){
        DataGeneratorService.init();
    }

    @isTest
    static void testGetApartmentRoomsByApartmentId() {
        Apartment__c apartment = [SELECT Id FROM Apartment__c LIMIT 1];
        insert new ApartmentRoom__c(Apartment__c = apartment.Id, Capacity__c = 5, Description__c = 'test', Price_Per_Night__c = 100, Name = 'test');
        List<ApartmentRoom__c> rooms = apartmentDataService.getRoomsByApartmentId(apartment.Id);

        Assert.areEqual(1, rooms.size());
        Assert.areEqual(apartment.Id, rooms.get(0).Apartment__c);
    }
}