force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/ApartmentType__c.field-meta.xml
<CustomField>
    <fullName>ApartmentType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment Type</label>
    <referenceTo>ApartmentType__c</referenceTo>
    <relationshipLabel>Apartments</relationshipLabel>
    <relationshipName>Apartments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApartmentType__c/ApartmentType__c.object-meta.xml
<CustomObject>
    <label>Apartment Type</label>
    <nameField>
        <label>Apartment Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/services/ApartmentDataServiceTest.cls
@isTest
private class ApartmentDataServiceTest {
    @testSetup
    static void setup() {
        Test.startTest();
        DataGeneratorService.init();
        Test.stopTest();
    }

    @isTest
    static void testGetApartments() {
        List<Apartment__c> apartmentsToTest = apartmentDataService.getApartments();
        List<Apartment__c> apartmentsWithIdExpected = [SELECT Id FROM Apartment__c];

        Assert.areEqual(
            apartmentsWithIdExpected.size(),
            apartmentsToTest.size()
        );
    }

    @isTest
    static void getGetApartmentTypes() {
        List<ApartmentType__c> apartmentTypesToTest = apartmentDataService.getApartmentTypes();
        List<ApartmentType__c> apartmentTypesWithIdExpected = [SELECT Id FROM ApartmentType__c];

        Assert.areEqual(
            apartmentTypesWithIdExpected.size(),
            apartmentTypesToTest.size()
        );
    }
}