force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApartmentReview__c/ApartmentReview__c.object-meta.xml
<CustomObject>
    <label>Apartment Review</label>
    <nameField>
        <label>Apartment Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartment Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApartmentReview__c/fields/Apartment__c.field-meta.xml
<CustomField>
    <fullName>Apartment__c</fullName>
    <label>Apartment</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipName>Apartment_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/controllers/ApartmentReviewControllerTest.cls
@isTest
public with sharing class ApartmentReviewControllerTest {
    @TestSetup
    static void setup(){
        DataGeneratorService.init();    
    }

    @isTest
    static void testGetReviewsByApartmentId() {
        Apartment__c apartment = [SELECT Id FROM Apartment__c LIMIT 1];
        insert new ApartmentReview__c(Apartment__c = apartment.Id, Comment__c = 'test', Rating__c = 5);
        List<apartmentReview__c> reviews = ApartmentReviewController.getReviewsByApartmentId(apartment.Id);

        Assert.areEqual(1, reviews.size());
    }
}