force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/ApartmentType__c.field-meta.xml
<CustomField>
    <fullName>ApartmentType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment Type</label>
    <referenceTo>ApartmentType__c</referenceTo>
    <relationshipLabel>Apartments</relationshipLabel>
    <relationshipName>Apartments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApartmentType__c/ApartmentType__c.object-meta.xml
<CustomObject>
    <label>Apartment Type</label>
    <nameField>
        <label>Apartment Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/services/DataGeneratorServiceTests.cls
@isTest
private class DataGeneratorServiceTests {
    @isTest
    static void initTest() {
        Test.startTest();
        DataGeneratorService.init();
        Test.stopTest();

        Assert.isTrue([SELECT COUNT() FROM Apartment__c] > 0, 'No Apartment__c were found');
        Assert.isTrue([SELECT COUNT() FROM ApartmentType__c] > 0, 'No ApartmentType__c were found');
        Assert.isTrue([SELECT COUNT() FROM Account] > 0, 'No Account was found');
        Assert.isTrue([SELECT COUNT() FROM Contact] > 0, 'No Contacts found');
    }

    @isTest
    static void getPriceForApartmentTypeNoTypeTest() {
        Assert.areEqual(500, DataGeneratorService.getPriceForApartmentType(''), 'The apartment price was calculated wrongly.');
    }
}