force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/ApartmentType__c.field-meta.xml
<CustomField>
    <fullName>ApartmentType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment Type</label>
    <referenceTo>ApartmentType__c</referenceTo>
    <relationshipLabel>Apartments</relationshipLabel>
    <relationshipName>Apartments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApartmentReservation__c/ApartmentReservation__c.object-meta.xml
<CustomObject>
    <label>Apartment Reservation</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Apartment Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apartment Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApartmentReservation__c/fields/Apartment__c.field-meta.xml
<CustomField>
    <fullName>Apartment__c</fullName>
    <label>Apartment</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipName>Apartment_Rentals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApartmentReservation__c/fields/ApartmentRoom__c.field-meta.xml
<CustomField>
    <fullName>ApartmentRoom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment Room</label>
    <referenceTo>ApartmentRoom__c</referenceTo>
    <relationshipLabel>Apartment Reservations</relationshipLabel>
    <relationshipName>Apartment_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApartmentReservation__c/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <label>Date From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ApartmentReservation__c/fields/DateTo__c.field-meta.xml
<CustomField>
    <fullName>DateTo__c</fullName>
    <label>Date To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ApartmentRoom__c/ApartmentRoom__c.object-meta.xml
<CustomObject>
    <label>Apartment Room</label>
    <nameField>
        <label>Apartment Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartment Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApartmentRoom__c/fields/Apartment__c.field-meta.xml
<CustomField>
    <fullName>Apartment__c</fullName>
    <label>Apartment</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipLabel>Apartment Rooms</relationshipLabel>
    <relationshipName>Apartment_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApartmentRoom__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApartmentRoom__c/fields/Price_Per_Night__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Night__c</fullName>
    <label>Price Per Night</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ApartmentType__c/ApartmentType__c.object-meta.xml
<CustomObject>
    <label>Apartment Type</label>
    <nameField>
        <label>Apartment Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/controllers/ApartmentSearchControllerTest.cls
@isTest
public with sharing class ApartmentSearchControllerTest {
    private static final String SYSTEM_ADMINISTRATOR = 'System Administrator';

    @TestSetup
    static void setup(){
        DataGeneratorService.init();
    }

    @isTest
    static void ApartmentSearchControllerTest() {
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = :SYSTEM_ADMINISTRATOR];
        String email = 'systemadminuser' + System.now().getTime() + '@testred.com';
        User adminUser = new User(
            Alias = 'sysad',
            Email = email,
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = adminProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = email
        );

        System.runAs(adminUser) {
            Assert.areEqual(SYSTEM_ADMINISTRATOR, ApartmentSearchController.getCurrentUserProfile());
        }
    }

    @isTest
    static void testGetApartmentReservations() {
        insert new ApartmentReservation__c(Apartment__c = [SELECT Id FROM Apartment__c LIMIT 1].Id, DateFrom__c = Date.today(), DateTo__c = Date.today(), Price__c = 100);
        List<ApartmentReservation__c> reservations = ApartmentSearchController.getAllReservations();

        Assert.areEqual(1, reservations.size());
    }

    @isTest
    static void testGetApartmentRooms() {
        Apartment__c apartment = [SELECT Id FROM Apartment__c LIMIT 1];
        insert new ApartmentRoom__c(Apartment__c = apartment.Id, Capacity__c = 5, Description__c = 'test', Price_Per_Night__c = 100, Name = 'test');

        Assert.areEqual(1, ApartmentSearchController.getAllRooms().size());
    }

    @isTest
    static void testGetApartmentsByLocation() {
        List<Apartment__c> apartment = [
            SELECT Id, Geolocation__Latitude__s, Geolocation__Longitude__s, apartmentType__r.Id
            FROM Apartment__c
            LIMIT 1
        ];
        List<Object> apartmentsByLocation = (List<Object>) JSON.deserializeUntyped(
            ApartmentSearchController.getApartmentsByLocation(
                apartment.get(0).Geolocation__Latitude__s,
                apartment.get(0).Geolocation__Longitude__s,
                apartment.get(0).apartmentType__r.Id
            )
        );
        List<Apartment__c> apartmentsExpected = [
            SELECT Id
            FROM Apartment__c
            WHERE apartmentType__c = :apartment.get(0).apartmentType__r.Id
            ORDER BY
                DISTANCE(
                    Geolocation__c,
                    GEOLOCATION(:apartment.get(0).Geolocation__Latitude__s, :apartment.get(0).Geolocation__Longitude__s),
                    'mi'
                )
            LIMIT 10
        ];

        Assert.areEqual(1, apartment.size());
        Assert.areEqual(
            apartmentsExpected.size(),
            apartmentsByLocation.size()
        );
    }
}