force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/ApartmentType__c.field-meta.xml
<CustomField>
    <fullName>ApartmentType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment Type</label>
    <referenceTo>ApartmentType__c</referenceTo>
    <relationshipLabel>Apartments</relationshipLabel>
    <relationshipName>Apartments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApartmentReservation__c/ApartmentReservation__c.object-meta.xml
<CustomObject>
    <label>Apartment Reservation</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Apartment Reservation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apartment Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApartmentReservation__c/fields/Apartment__c.field-meta.xml
<CustomField>
    <fullName>Apartment__c</fullName>
    <label>Apartment</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipName>Apartment_Rentals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApartmentReservation__c/fields/ApartmentRoom__c.field-meta.xml
<CustomField>
    <fullName>ApartmentRoom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment Room</label>
    <referenceTo>ApartmentRoom__c</referenceTo>
    <relationshipLabel>Apartment Reservations</relationshipLabel>
    <relationshipName>Apartment_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApartmentReservation__c/fields/DateFrom__c.field-meta.xml
<CustomField>
    <fullName>DateFrom__c</fullName>
    <label>Date From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ApartmentReservation__c/fields/DateTo__c.field-meta.xml
<CustomField>
    <fullName>DateTo__c</fullName>
    <label>Date To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ApartmentRoom__c/ApartmentRoom__c.object-meta.xml
<CustomObject>
    <label>Apartment Room</label>
    <nameField>
        <label>Apartment Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartment Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApartmentRoom__c/fields/Apartment__c.field-meta.xml
<CustomField>
    <fullName>Apartment__c</fullName>
    <label>Apartment</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipLabel>Apartment Rooms</relationshipLabel>
    <relationshipName>Apartment_Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApartmentRoom__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApartmentRoom__c/fields/Price_Per_Night__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Night__c</fullName>
    <label>Price Per Night</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ApartmentType__c/ApartmentType__c.object-meta.xml
<CustomObject>
    <label>Apartment Type</label>
    <nameField>
        <label>Apartment Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/controllers/ApartmentSearchController.cls
public without sharing class ApartmentSearchController {
    @AuraEnabled(cacheable=true)
    public static String getCurrentUserProfile() {
        return [SELECT Name FROM Profile WHERE Id = :UserInfo.getProfileId() LIMIT 1].Name;
    }

    @AuraEnabled(cacheable=true)
    public static List<ApartmentReservation__c> getAllReservations() {
        return [SELECT Apartment__c, DateFrom__c, DateTo__c, ApartmentRoom__c FROM ApartmentReservation__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<ApartmentRoom__c> getAllRooms(){
        return [SELECT Name, Apartment__c, Description__c, Capacity__c, Price_Per_Night__c FROM ApartmentRoom__c];
    }

    @AuraEnabled(cacheable=true)
    public static String getApartmentsByLocation(Decimal latitude, Decimal longitude, String apartmentTypeId) {
        String query = 'SELECT Name, Geolocation__Latitude__s, Geolocation__Longitude__s FROM Apartment__c ';
        if (String.isNotBlank(apartmentTypeId)) {
            query += 'WHERE ApartmentType__c = :apartmentTypeId ';
        }
        query += ' WITH SECURITY_ENFORCED ORDER BY DISTANCE(Geolocation__c, GEOLOCATION(:latitude, :longitude), \'mi\') LIMIT 10';
        return JSON.serialize(Database.query(query));
    }
}