force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApartmentReview__c/ApartmentReview__c.object-meta.xml
<CustomObject>
    <label>Apartment Review</label>
    <nameField>
        <label>Apartment Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartment Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApartmentReview__c/fields/Apartment__c.field-meta.xml
<CustomField>
    <fullName>Apartment__c</fullName>
    <label>Apartment</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipName>Apartment_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/controllers/ApartmentReviewController.cls
public without sharing class ApartmentReviewController {
    @AuraEnabled(cacheable=true)
    public static List<ApartmentReview__c> getReviewsByApartmentId(Id apartmentId) {
        return [
            SELECT
                Id,
                Name,
                Comment__c,
                Rating__c,
                LastModifiedDate,
                CreatedDate,
                CreatedBy.Name,
                CreatedBy.SmallPhotoUrl,
                CreatedBy.CompanyName
            FROM ApartmentReview__c
            WHERE Apartment__c = :apartmentId
            ORDER BY CreatedDate DESC
        ];
    }
}