force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Apartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/ApartmentType__c.field-meta.xml
<CustomField>
    <fullName>ApartmentType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apartment Type</label>
    <referenceTo>ApartmentType__c</referenceTo>
    <relationshipLabel>Apartments</relationshipLabel>
    <relationshipName>Apartments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApartmentType__c/ApartmentType__c.object-meta.xml
<CustomObject>
    <label>Apartment Type</label>
    <nameField>
        <label>Apartment Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/controllers/SimilarApartmentsControllerTest.cls
@isTest
private class SimilarApartmentsControllerTest {
    @testSetup
    static void setup() {
        Test.startTest();
        DataGeneratorService.init();
        Test.stopTest();
    }

    @isTest
    static void getSimilarApartmentsByCountryTest() {
        List<ApartmentType__c> apartmentTypes = ApartmentDataService.getApartmentTypes();

        List<Apartment__c> apartmentsByType = SimilarApartmentsController.getSimilarApartments(
            [SELECT Id FROM Apartment__c LIMIT 1].Id,
            SimilarApartmentsController.COUNTRY_TYPE
        );

        Assert.isFalse(apartmentTypes.isEmpty(), 'The there are no apartment Type records.');
        Assert.isFalse(
            apartmentsByType.isEmpty(),
            'The similar Apartments by type query did not return the right amount.'
        );
    }

    @isTest
    static void getSimilarApartmentsByTypeTest() {
        List<ApartmentType__c> apartmentTypes = ApartmentDataService.getApartmentTypes();

        List<Apartment__c> apartmentsByType = SimilarApartmentsController.getSimilarApartments(
            [SELECT Id FROM Apartment__c LIMIT 1].Id,
            SimilarApartmentsController.TYPE_TYPE
        );

        Assert.isFalse(apartmentTypes.isEmpty(), 'The there are no apartment Type records.');
        Assert.isFalse(
            apartmentsByType.isEmpty(),
            'The similar Apartments by type query did not return the right amount.'
        );
    }

    @isTest
    static void getSimilarApartmentsParentApartmentEmptyTest() {
        Assert.isTrue(SimilarApartmentsController.getSimilarApartments(null, '').isEmpty(), 'The similar Apartments should be empty.');
    }
}